### ISSUE TITLE
Can I manage vim versions with everyenv?

### ISSUE THREAD

**Issue by bruno-** [mislav/anyenv#1]
Hey,
can I use `everyenv` to manage vim versions on my system?

For example, on OSX there's a system vim in `/usr/bin/vim`. I also wanna install latest stable release via brew and the latest version from `HEAD`.
Now I'd like to be able to see which versions I have installed and easily switch from one to another for the purpose of playing and debugging. Having a `.ruby-version` file equivalent is not important at all.

Would this be possible? And how?

Thanks a lot!

**Comment by mislav** [comment]
Good question! You should be able to manage multiple versions of _anything_ with this project, including vim. Here's how I would try it:
1. `PROGRAM_NAME=vimenv PROGRAM_EXECUTABLE=vim make`
2. Move `vimenv` into PATH
3. Follow the instruction in `vimenv init` to add the initialization line to your shell profile
4. Install or symlink vim versions into `~/.vimenv/versions/*`
5. Open another shell window
6. MAGIC! :tada: `vimenv versions` should show available versions. Switch between them with `vimenv global <version>`. Or, use `vimenv shell <version>` to change the version temporarily only in the currently active shell instance.

**Comment by bruno-** [comment]
Thanks Mislav, I'll give it a try.
